DATABASE:
  DB_NAME: "pg_tools"
  USERNAME: "root"
  PASSWORD: ""

REDIS:
  PASSWORD: ""

RABBITMQ:
  USERNAME: "guest"
  PASSWORD: "guest"

SNAP_CORE_KEY: ""
SNAP_CORE_SECRET: ""

SECURITY:
  JWT_SECRET_KEY: "sN4pKeyPr0c#24i3o?"

NEW_RELIC_LICENSE_KEY: "1234567890123456789012345678901234567890"
INTERNAL_SERVICE_KEY: ""